import { query } from '../db/pool.js';
function similarity(a,b){const ta=new Set(`${a||''}`.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2));const tb=new Set(`${b||''}`.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2));if(!ta.size||!tb.size)return 0;let inter=0;for(const x of ta)if(tb.has(x))inter++;return inter/(ta.size+tb.size-inter);}
export async function linkOrCreateIssue({complaint,category,departmentId,jurisdictionId,officerId,priority,aiCandidates=[]}){
 let best=null; for(const cand of aiCandidates){const s=similarity(`${complaint.problem_report} ${complaint.problem_details}`,`${cand.problem_report} ${cand.problem_details}`);if(s>=0.42 && (!best||s>best.similarity))best={...cand,similarity:s};}
 if(!best){const nearby=await query(`SELECT c.id,c.problem_report,c.problem_details,c.civic_issue_id FROM complaints c WHERE c.id<>$1 AND c.problem_type_id=(SELECT id FROM problem_types WHERE code=$2) AND c.pincode=$3 ORDER BY c.created_at DESC LIMIT 50`,[complaint.id,category,complaint.pincode]);for(const cand of nearby.rows){const s=similarity(`${complaint.problem_report} ${complaint.problem_details}`,`${cand.problem_report} ${cand.problem_details}`);if(s>=0.55 && (!best||s>best.similarity))best={...cand,similarity:s};}}
 let issueId=null;
 if(best?.civic_issue_id) issueId=best.civic_issue_id;
 if(!issueId){const r=await query(`SELECT id FROM civic_issues WHERE problem_type_id=(SELECT id FROM problem_types WHERE code=$1) AND pincode=$2 AND lower(taluk)=lower($3) ORDER BY updated_at DESC LIMIT 1`,[category,complaint.pincode,complaint.taluk]); issueId=r.rows[0]?.id||null;}
 if(!issueId){const r=await query(`INSERT INTO civic_issues(title,summary,problem_type_id,department_id,jurisdiction_id,officer_id,pincode,taluk,panchayat,report_count,estimated_affected,health_risk,impact_score,priority_score) VALUES($1,$2,(SELECT id FROM problem_types WHERE code=$3),$4,$5,$6,$7,$8,$9,0,$10,$11,$12,$13) RETURNING id`,[`Emerging ${category.replaceAll('_',' ').toLowerCase()} issue`,`Community reports are being consolidated into one underlying Civic Issue.`,category,departmentId,jurisdictionId,officerId,complaint.pincode,complaint.taluk,complaint.panchayat,complaint.people_affected,complaint.health_risk,priority.impactScore,priority.priorityScore]);issueId=r.rows[0].id;}
 const count=await query('SELECT count(*)::int n,coalesce(sum(people_affected),0)::int affected FROM complaints WHERE civic_issue_id=$1 OR id=$2',[issueId,complaint.id]);
 await query('INSERT INTO issue_reports(complaint_id,civic_issue_id,similarity,linked_by) VALUES($1,$2,$3,$4) ON CONFLICT(complaint_id) DO UPDATE SET civic_issue_id=EXCLUDED.civic_issue_id,similarity=EXCLUDED.similarity,linked_by=EXCLUDED.linked_by',[complaint.id,issueId,best?.similarity||1,best?'AI+RULE':'RULE']);
 await query('UPDATE complaints SET civic_issue_id=$1 WHERE id=$2',[issueId,complaint.id]);
 await query(`UPDATE civic_issues SET report_count=(SELECT count(*) FROM issue_reports WHERE civic_issue_id=$1),estimated_affected=(SELECT coalesce(sum(c.people_affected),0) FROM complaints c WHERE c.civic_issue_id=$1),updated_at=now(),department_id=coalesce($2,department_id),jurisdiction_id=coalesce($3,jurisdiction_id),officer_id=coalesce($4,officer_id),impact_score=$5,priority_score=$6 WHERE id=$1`,[issueId,departmentId,jurisdictionId,officerId,priority.impactScore,priority.priorityScore]);
 return {issueId,linkedComplaintId:best?.id||null,similarity:best?.similarity||1};
}
